# This is a basic workflow to help you get started with Actions

name: build_dev_pkg

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: ct
        with:
          format: YYYYMMDD-HH
          utcOffset: "+08:00"
      - uses: actions/checkout@v2
      - name: build with pyinstaller
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.5
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: install requirements.txt
        run: pip install -r requirements.txt
      - name: install pyinstaller
        run: pip install pyinstaller
      - name: run pyinstaller command
        env:
          BUILD_TIME: "${{ steps.ct.outputs.year }}${{ steps.ct.outputs.month }}${{ steps.ct.outputs.day }}_${{ steps.ct.outputs.hour }}${{ steps.ct.outputs.minute }}${{ steps.ct.outputs.second }}"
        run: pyinstaller -i logo.ico -n XstreamDL-CLI_dev_${{ env.BUILD_TIME }} -F XstreamDL_CLI\__main__.py
      - name: Upload Artifact
        env:
          BUILD_TIME: "${{ steps.ct.outputs.year }}${{ steps.ct.outputs.month }}${{ steps.ct.outputs.day }}_${{ steps.ct.outputs.hour }}${{ steps.ct.outputs.minute }}${{ steps.ct.outputs.second }}"
        uses: actions/upload-artifact@v1.0.0
        with:
          name: XstreamDL-CLI_dev_${{ env.BUILD_TIME }}
          path: dist\XstreamDL-CLI_dev_${{ env.BUILD_TIME }}.exe
